set nocompatible
set encoding=utf-8
set relativenumber
set ruler
set ignorecase
set smartcase
set shiftwidth=4
set tabstop=4 softtabstop=0
set expandtab
set backupdir=~/.vim/backup//,.
set directory=~/.vim/swap//,.

if has('filetype')
  filetype plugin indent on
endif

if has('syntax')
  syntax on
  set background=dark
  colorscheme solarized
endif

if has('mouse')
  set mouse=a
endif

if has('autocmd')
  autocmd FileType gitcommit setlocal textwidth=72
  autocmd FileType gitcommit,markdown,text setlocal spell spelllang=en_us
  autocmd FileType go,make setlocal noexpandtab
  autocmd FileType html,markdown,yaml setlocal shiftwidth=2 tabstop=2
endif

if has('persistent_undo')
  set undodir=~/.vim/undo,.
  set undofile
endif
